/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZustandIndexRouteImport } from './routes/zustand/index'
import { Route as ReduxIndexRouteImport } from './routes/redux/index'
import { Route as ReactQueryIndexRouteImport } from './routes/react-query/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZustandIndexRoute = ZustandIndexRouteImport.update({
  id: '/zustand/',
  path: '/zustand/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReduxIndexRoute = ReduxIndexRouteImport.update({
  id: '/redux/',
  path: '/redux/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactQueryIndexRoute = ReactQueryIndexRouteImport.update({
  id: '/react-query/',
  path: '/react-query/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/react-query/': typeof ReactQueryIndexRoute
  '/redux/': typeof ReduxIndexRoute
  '/zustand/': typeof ZustandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/react-query': typeof ReactQueryIndexRoute
  '/redux': typeof ReduxIndexRoute
  '/zustand': typeof ZustandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/react-query/': typeof ReactQueryIndexRoute
  '/redux/': typeof ReduxIndexRoute
  '/zustand/': typeof ZustandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/react-query/' | '/redux/' | '/zustand/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/react-query' | '/redux' | '/zustand'
  id: '__root__' | '/' | '/react-query/' | '/redux/' | '/zustand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReactQueryIndexRoute: typeof ReactQueryIndexRoute
  ReduxIndexRoute: typeof ReduxIndexRoute
  ZustandIndexRoute: typeof ZustandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zustand/': {
      id: '/zustand/'
      path: '/zustand'
      fullPath: '/zustand/'
      preLoaderRoute: typeof ZustandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redux/': {
      id: '/redux/'
      path: '/redux'
      fullPath: '/redux/'
      preLoaderRoute: typeof ReduxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-query/': {
      id: '/react-query/'
      path: '/react-query'
      fullPath: '/react-query/'
      preLoaderRoute: typeof ReactQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReactQueryIndexRoute: ReactQueryIndexRoute,
  ReduxIndexRoute: ReduxIndexRoute,
  ZustandIndexRoute: ZustandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
